{"name": "Attempted login with invalid credentials and some empty data -- @1.3 ", "status": "passed", "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1717323202226, "stop": 1717323210836}, {"name": "When I fill in \"username\" with \"standard_user\"", "status": "passed", "start": 1717323210836, "stop": 1717323211004}, {"name": "And I fill in \"Password\" with \"standarduser321\"", "status": "passed", "start": 1717323211004, "stop": 1717323211146}, {"name": "And I press \"Login\"", "status": "passed", "start": 1717323211146, "stop": 1717323211202}, {"name": "Then I should see the error message \"Epic sadface: Username and password do not match any user in this service\"", "status": "passed", "start": 1717323211203, "stop": 1717323211225}], "parameters": [{"name": "username", "value": "standard_user"}, {"name": "password", "value": "standarduser321"}, {"name": "error_message", "value": "Epic sadface: Username and password do not match any user in this service"}], "start": 1717323202225, "stop": 1717323213300, "uuid": "1f436cf2-1036-463e-8afe-3fee89d8c957", "historyId": "8bd5c9e22921ff0a4bb74b02f1ff4e12", "fullName": "Login: Attempted login with invalid credentials and some empty data", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "negative"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}